name: Feature Branch Validation and PR

on:
  push:
    branches:
      - 'feature/**'

jobs:
  validate-rules:
    name: Validate Detection Rules
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          
      - name: Run tests
        run: |
          echo "Running detection rules tests..."
          python -m detection_rules test
          
  create-pull-request:
    name: Create Pull Request
    needs: validate-rules
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          base: main
          title: '[Detection Rule] ${{ steps.extract_branch.outputs.branch }}'
          body: |
            ## Detection Rule Submission
            
            **Branch:** ${{ steps.extract_branch.outputs.branch }}
            **Author:** @${{ github.actor }}
            **Validation Status:** ✅ Passed
            
            ### Test Results
            - ✅ Detection rules tests passed
            
            ### Review Checklist
            - [ ] Rule syntax is correct
            - [ ] Rule logic is appropriate for the threat
            - [ ] Rule has appropriate severity level
            - [ ] Rule includes proper metadata
            - [ ] Rule has been tested in development environment
            
            ---
            @detection-team-lead Please review this detection rule submission.
            
          assignees: detection-team-lead
          reviewers: detection-team-lead
          labels: |
            detection-rule
            needs-review
            automated-pr